# Generated by Django 5.2.18 on 2026-10-08 14:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=160)),
                ("current_revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(default="follow_up_created", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="case_storage.approval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("content_digest", models.CharField(max_length=64)),
                ("invoice", models.JSONField()),
                ("register", models.JSONField()),
                ("manifest", models.JSONField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="case_storage.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("sha256", models.CharField(max_length=64)),
                ("content", models.BinaryField()),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="case_storage.caserevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task",
                        to="case_storage.approval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "identity",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enrollment_id", models.UUIDField(null=True)),
                ("enrollment_digest", models.CharField(blank=True, max_length=64)),
                (
                    "owner",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("can_review", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_storage.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="case_storage.caserevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="approval",
            name="proposal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="case_storage.proposal"
            ),
        ),
        migrations.AddConstraint(
            model_name="caserevision",
            constraint=models.UniqueConstraint(fields=("case", "number"), name="one_case_revision"),
        ),
        migrations.AddConstraint(
            model_name="caserevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1)), name="positive_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencedocument",
            constraint=models.UniqueConstraint(fields=("revision", "name"), name="one_document"),
        ),
        migrations.AddConstraint(
            model_name="installation",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="one_installation"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("case", "user"), name="one_membership"),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(fields=("revision", "digest"), name="one_proposal"),
        ),
    ]
